# fly.toml file generated for mtg-treachery on 2023-07-14T17:34:38-07:00

app = "mtg-treachery"
kill_signal = "SIGTERM"
kill_timeout = 5
mounts = []
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "mtg-treachery.fly.dev"
  PORT = "8080"
  RELEASE_COOKIE = "0kPSOX1tC91xaRitftGCOF6Rgtl8bGpZbxPhx3xkF4d8aUpUTtQ0Hw=="

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443